pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'chmod +x build.sh'
        sh './build.sh'
      }
    }
     stage('Deploy') {
            steps {
                script {
                    def BRANCH_NAME = env.GIT_BRANCH.split('/').last()
                    echo "Current branch is: ${BRANCH_NAME}"
                    // Perform actions based on BRANCH_NAME
                  sh 'docker-compose down'      
                          
                 if ( "${BRANCH_NAME}" == "dev" ) {
                      sh 'chmod +x build.sh'
                      sh './build.sh'
                      echo "haiiii dev"            
                      docker tag nginximage smart24/dev
                      docker push smart24/dev
                      echo "Docker image pushed successfully."
                 } else if ( "${BRANCH_NAME}" == "main" ) {
                      sh 'chmod +x build.sh'
                      sh './build.sh'
                      echo "mainnnnnnn"
                      docker tag nginximage smart24/dev
                      docker push smart24/dev
                      echo "Docker image pushed successfully."
                } else {
                  echo "Branch not configured for deployment"  exit 1 
                  }
            
                }
            }
        }
     
        }
      }
   
    
  
    

  




             
              
  

                 
    
  
    

  
