pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'chmod +x build.sh'
        sh './build.sh'
      }
    }
     stage('Deploy') {
            steps {
                script {
                    def BRANCH_NAME = env.GIT_BRANCH.split('/').last()
                    echo "Current branch is: ${BRANCH_NAME}"
                    // Perform actions based on BRANCH_NAME
                  sh 'docker-compose down'      
                  
                 
                 if ( "${BRANCH_NAME}" == "dev" ) 
                 then {
                      sh 'chmod +x build.sh'
                      sh './build.sh'
                      echo "haiiii dev"

                      DOCKER_REPO="smart24/dev:latest"
                      docker tag nginximage:${BUILD_NUMBER} $DOCKER_REPO:${BUILD_NUMBER}
                      docker push $DOCKER_REPO:${BUILD_NUMBER}
                      docker push $DOCKER_REPO:latest
                      echo "Docker image pushed successfully."
                else if ( "${BRANCH_NAME}" == "main" ) 
                then {
                      sh 'chmod +x build.sh'
                      sh './build.sh'
                      echo "mainnnnnnn"

                      DOCKER_REPO="smart24/prod:latest"
                      docker tag nginximage:${BUILD_NUMBER} $DOCKER_REPO:${BUILD_NUMBER}
                      docker push $DOCKER_REPO:${BUILD_NUMBER}
                      docker push $DOCKER_REPO:latest
                      echo "Docker image pushed successfully."
                     

              else {
                  echo "Branch not configured for deployment"  exit 1 
                  }
            
                }
            }
        }
     
        }
      }
   
    
  
    

  




             
              
  

                 
    
  
    

  
