pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'chmod +x build.sh'
        sh './build.sh'
      }
    }
     stage('Deploy') {
            steps {
          
          withCredentials([usernamePassword(credentialsId: "${DOCKER_REGISTRY_CREDS}", passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
          sh "echo \$DOCKER_PASSWORD | docker login -u \$DOCKER_USERNAME --password-stdin docker.io"
          
                script {
                    def BRANCH_NAME = env.GIT_BRANCH.split('/').last()
                    echo "Current branch is: ${BRANCH_NAME}"
                    // Perform actions based on BRANCH_NAME
                  sh 'docker-compose down'      
                          
                 if ( "${BRANCH_NAME}" == "dev" ) {
                      sh 'chmod +x build.sh'
                      sh './build.sh'
                      echo "haiiii dev"            
                      docker tag nginximage smart24/img
                      docker push smart24/img
                      echo "Docker image pushed successfully."
                 } else if ( "${BRANCH_NAME}" == "main" ) {
                      sh 'chmod +x build.sh'
                      sh './build.sh'
                      echo "mainnnnnnn"
                      docker tag nginximage smart24/prod
                      docker push smart24/prod
                      echo "Docker image pushed successfully."
                } else {
                  echo "Branch not configured for deployment"  exit 1 
                  }
            
                }
            }
        }
     
        }
      }
   
    
  
    

  




             
              
  

                 
    
  
    

  
